_BASE_: MinVIS_R50.yaml
MODEL:
  META_ARCHITECTURE: "CTMinVIS"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_dvisPlus"
    REID_BRANCH: True
  CL_PLUGIN:
    NUM_NEGATIVES: 99
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (70000, 90000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 10000
#SOLVER:
#  IMS_PER_BATCH: 1
#  STEPS: (14000, 18000)
#  MAX_ITER: 20000
#  CHECKPOINT_PERIOD: 5000

INPUT:
  #  SAMPLING_FRAME_NUM: 5
  #  SAMPLING_FRAME_RANGE: 10
  SAMPLING_FRAME_NUM: 10
  SAMPLING_FRAME_RANGE: 20
  MIN_SIZE_TEST: 720
  CROP:
    ENABLED: False
  PSEUDO:
    CROP:
      ENABLED: False
LOSS_WEIGHTING: 'none' # 'none', 'log', 'linear', 'power_law'
POWER_LAW_EXPONENT: 0.5
OUTPUT_DIR: './output_CTVIS_R50_4DOR_withsimstation'
